### ISSUE TITLE
I would like to ask about the specific configuration environment

### ISSUE THREAD

**Issue by Lfang905** [anatole33/SR-secure#1]
Hello, author, I read your paper and want to repeat the code in the article. However, in the configuration environment, I use Python3.9 version, and there is no way to implement the code running in the environment when installing other packages. I would like to ask about the specific version.

**Comment by radu1** [comment]
Thank you for your interest in our paper and our code.
I have just tested again our scripts as described at [https://github.com/anatole33/SR-secure/](https://github.com/anatole33/SR-secure/)
In particular, I had no problem when testing install-python-and-libraries.sh and then I had no problem when testing the other scripts to reproduce our figures.
My OS is Ubuntu 22.04.3 LTS and I have Python 3.10.12.

**Comment by anatole33** [comment]
Also the project has been initially developed on Ubuntu 18.04.3 and using python 3.6.9
I hope this helps
